In [4]:
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
from rdkit.Chem import Descriptors
from rdkit.Chem import rdMolDescriptors
from rdkit import DataStructs

In [5]:
df = pd.read_csv('final_total', sep=' ', na_values=['na'])

In [6]:
df

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,23.0,60.0
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,10000.0,10000.0
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,183.0,224200.0
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,11790.0,12250.0
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,14610.0,30230.0
...,...,...,...,...
800,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,1230.0,11240.0
801,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,56450.0,7450.0
802,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,10000.0,450.0
803,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,50.0,10000.0
804,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,53.9,53.0

In [7]:
df['ido_ic50'].astype('float64')

0         23.0
1      10000.0
2        183.0
3      11790.0
4      14610.0
        ...
800     1230.0
801    56450.0
802    10000.0
803       50.0
804       53.9
Name: ido_ic50, Length: 805, dtype: float64

In [8]:
df.dtypes

CHEMBLID     object
smiles       object
ido_ic50    float64
tdo_ic50    float64
dtype: object

In [9]:
df2 = df.dropna(ignore_index=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 760 entries, 0 to 759
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CHEMBLID  760 non-null    object
 1   smiles    760 non-null    object
 2   ido_ic50  760 non-null    float64
 3   tdo_ic50  760 non-null    float64
dtypes: float64(2), object(2)
memory usage: 23.9+ KB

In [10]:
df2

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,23.0,60.0
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,10000.0,10000.0
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,183.0,224200.0
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,11790.0,12250.0
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,14610.0,30230.0
...,...,...,...,...
755,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,1230.0,11240.0
756,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,56450.0,7450.0
757,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,10000.0,450.0
758,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,50.0,10000.0
759,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,53.9,53.0

In [12]:
df2.loc[:, 'ido_ic50'] = (np.log10((df2.loc[:, 'ido_ic50'])*10**(-9)))*(-1)

In [13]:
df2.loc[:, 'tdo_ic50'] = (np.log10((df2.loc[:, 'tdo_ic50'])*10**(-9)))*(-1)

In [14]:
df2

,CHEMBLID,smiles,ido_ic50,tdo_ic50
0,CHEMBL1098875,O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O,7.638272,7.221849
1,CHEMBL1209728,Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C,5.000000,5.000000
2,CHEMBL1276265,O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O,6.737549,3.649364
3,CHEMBL1346056,Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1,4.928486,4.911864
4,CHEMBL139935,O=[N+]([O-])c1cc(F)c2cccnc2c1O,4.835350,4.519562
...,...,...,...,...
755,CHEMBL5221020,O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12,5.910095,4.949234
756,CHEMBL5221102,Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1,4.248336,5.127844
757,CHEMBL578036,CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1,5.000000,6.346787
758,CHEMBL584991,Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1,7.301030,5.000000
759,CHEMBL72165,O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O,7.268411,7.275724

In [37]:
df3 = df2.loc[:, ['ido_ic50', 'tdo_ic50']]
df3.to_csv('target_columns.csv', index_label=False)

In [43]:
df2.smiles.to_csv('smiles.txt', sep=' ')

In [15]:
df2['smiles']

0                O=C1c2cc(F)ccc2-n2c1nc1ccccc1c2=O
1      Cc1c(Br)oc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C
2               O=C1c2ccc(Cl)cc2-n2c1nc1ccccc1c2=O
3           Oc1ccccc1-c1nc2c3ccccc3c3ccccc3c2[nH]1
4                   O=[N+]([O-])c1cc(F)c2cccnc2c1O
                          ...
755       O[C@@H]1CCCC[C@H]1CNc1c(Br)ccc2[nH]ncc12
756              Brc1cc(NC[C@H]2CCCN2)c2cn[nH]c2c1
757     CC1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(CO)coc2-1
758               Nc1nonc1/C(=N/O)Nc1ccc(F)c(Cl)c1
759             O=C1c2cc(Br)ccc2-n2c1nc1ccccc1c2=O
Name: smiles, Length: 760, dtype: object

In [16]:
from rdkit.Chem import SaltRemover as sr
remover = sr.SaltRemover()

In [17]:
mols = []
for i in range(len(df2['smiles'])):
    mol_i = Chem.MolFromSmiles(df2['smiles'][i])
    mol_i = remover.StripMol(mol_i, dontRemoveEverything=True)
    mols.append(mol_i)
len(mols)

760

In [49]:
with Chem.SDWriter('760mols.sdf') as f:
    for mol in mols:
        f.write(mol)

In [18]:
#Calculating Descriptors
i = 0
descriptors = []
for mol in mols:
    descriptors.append(Descriptors.CalcMolDescriptors(mols[i]).values())
    i += 1
len(descriptors)

760

In [19]:
df10 = pd.DataFrame(descriptors, columns=Descriptors.CalcMolDescriptors(mols[0]).keys())

In [20]:
df10

,MaxAbsEStateIndex,MaxEStateIndex,MinAbsEStateIndex,MinEStateIndex,qed,SPS,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,13.277519,13.277519,0.036389,-0.511565,0.489318,12.550000,266.231,259.175,266.049156,96,...,0,0,0,0,0,0,0,0,0,0
1,12.817228,12.817228,0.033613,-0.447936,0.610144,18.434783,373.246,356.110,372.036107,118,...,0,0,0,0,0,0,0,0,0,0
2,12.567572,12.567572,0.144414,-0.250445,0.498010,12.550000,282.686,275.630,282.019605,96,...,0,0,0,0,0,0,0,0,0,0
3,10.155652,10.155652,0.227007,0.227007,0.415814,11.500000,310.356,296.244,310.110613,114,...,0,0,0,0,0,0,0,0,0,0
4,13.331481,13.331481,0.056111,-0.854630,0.573824,10.466667,208.148,203.108,208.028420,76,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,10.019296,10.019296,0.163353,-0.163353,0.811838,23.684211,324.222,306.078,323.063324,102,...,0,0,0,0,0,0,0,0,0,0
756,4.081375,4.081375,0.593456,0.593456,0.815194,19.941176,295.184,280.064,294.048009,90,...,0,0,0,0,0,0,0,0,0,0
757,12.755531,12.755531,0.005596,-0.567519,0.819410,18.391304,310.349,292.205,310.120509,118,...,0,0,0,0,0,0,0,0,0,0
758,12.958814,12.958814,0.025877,-0.562666,0.331791,11.555556,271.639,264.583,271.027230,94,...,0,0,0,0,0,0,0,0,0,0
759,12.572565,12.572565,0.182222,-0.218377,0.498937,12.550000,327.137,320.081,325.969090,96,...,0,0,0,0,0,0,0,0,0,0

In [61]:
df10.to_csv('all_descriptors.csv', index=False)

In [21]:
#RDKit fingerprint
fpgen1 = AllChem.GetRDKitFPGenerator(fpSize=2048, maxPath=7)
i = 0
l1 = np.zeros((760, 2048), dtype='uint8')
for mol in mols:
    fp1 = fpgen1.GetFingerprintAsNumPy(mols[i])
    l1[i, :] = fp1
    i += 1
rdfp1 = l1
rdfp1.shape 
rdfp1.sum()

687754

In [98]:
#Morgan Fingerprints:
fpgen2 = AllChem.GetMorganGenerator()
i = 0
l2 = np.zeros((1, 2048), dtype='uint8')
for mol in mols:
    fp2 = fpgen2.GetFingerprintAsNumPy(mols[i])
    l2 = np.vstack((l2, fp2))
    i += 1
mfp = l2[1:, :]
mfp.shape
mfp.sum()

45791