In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.svm import SVR
from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV
from sklearn.metrics import roc_curve, RocCurveDisplay, auc, roc_auc_score
from sklearn.preprocessing import LabelEncoder

In [2]:
df1 = pd.read_csv('final_descriptors.csv')

In [3]:
df2 = pd.read_csv('target_columns.csv')

In [4]:
for i in range(760):
    if df2['ido_ic50'].values[i] >= 6.15:
        df2['ido_ic50'].values[i] = 1
    else:
        df2['ido_ic50'].values[i] = 0

In [5]:
for i in range(760):
    if df2['tdo_ic50'].values[i] >= 6.00:
        df2['tdo_ic50'].values[i] = 1
    else:
        df2['tdo_ic50'].values[i] = 0

In [6]:
df2['tdo_ic50'] = df2['tdo_ic50'].astype('category')
df2['ido_ic50'] = df2['ido_ic50'].astype('category')

In [7]:
df = pd.concat([df1, df2], axis=1)

In [8]:
df.dropna(axis=0, inplace=True, ignore_index=True)

In [89]:
df.loc[:, ['ido_ic50', 'tdo_ic50']].to_csv('target2_columns.csv', index=False)

In [10]:
pd.read_csv('target2_columns.csv')

     ido_ic50  tdo_ic50
0         1.0       1.0
1         0.0       0.0
2         1.0       0.0
3         0.0       0.0
4         0.0       0.0
..        ...       ...
752       0.0       0.0
753       0.0       0.0
754       0.0       1.0
755       1.0       0.0
756       1.0       1.0

[757 rows x 2 columns]

In [12]:
y1 = df['ido_ic50']
y2 = df['tdo_ic50']

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
x = df.drop(['ido_ic50', 'tdo_ic50'], axis=1)

In [15]:
x_scaled = StandardScaler().fit_transform(x)
x_scaled = pd.DataFrame(x_scaled, columns=x.columns)

In [16]:
estimator = LinearSVC(dual=False)

In [17]:
rfe = RFE(estimator, n_features_to_select=50, step=1)

In [18]:
####################################   IDO
rfe1 = rfe.fit(x_scaled, y1)

In [62]:
ido_des_rfe = pd.DataFrame(x, columns=x.columns[rfe1.support_])
ido_des_rfe.to_csv('ido_des_rfe.csv', index_label=False)

In [20]:
###################################################  TDO
rfe2 = rfe.fit(x_scaled, y2)

In [67]:
tdo_des_rfe = pd.DataFrame(x, columns=x.columns[rfe2.support_])
tdo_des_rfe.to_csv('tdo_des_rfe.csv', index_label=False)

In [68]:
pd.read_csv('tdo_des_rfe.csv')

,qed,MaxPartialCharge,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_MWHI,BalabanJ,Chi0v,Chi3n,Chi3v,Kappa3,...,fr_Ar_NH,fr_NH2,fr_Nhpyrrole,fr_amide,fr_amidine,fr_ether,fr_furan,fr_pyridine,fr_thiophene,fr_urea
0,0.489318,0.265850,1.850000,2.700000,19.142144,2.196267,10.130340,3.422924,3.422924,1.261965,...,0,0,0,0,0,0,0,0,0,0
1,0.610144,0.237258,1.826087,2.565217,79.918731,2.078932,14.964727,5.264118,6.020737,1.874356,...,0,0,0,0,0,0,1,0,0,0
2,0.498010,0.265850,1.850000,2.700000,35.495691,2.213612,10.886269,3.424103,3.659200,1.338652,...,0,0,0,0,0,0,0,0,0,0
3,0.415814,0.141781,1.250000,2.000000,16.255462,1.978942,12.822630,4.531742,4.531742,1.752740,...,1,0,1,0,0,0,0,0,0,0
4,0.573824,0.315479,2.266667,2.933333,19.142178,2.903274,7.345503,1.992077,1.992077,1.354345,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,0.811838,0.067149,2.210526,3.052632,79.918731,1.771904,12.280673,3.983299,4.644131,2.623076,...,1,0,1,0,0,0,0,0,0,0
753,0.815194,0.068191,2.411765,3.235294,79.918731,1.805917,11.049003,3.224730,3.682568,2.301831,...,1,0,1,0,0,0,0,0,0,0
754,0.819410,0.237313,1.913043,2.652174,16.336776,2.042118,13.232436,5.213113,5.213113,1.814473,...,0,0,0,0,0,0,1,0,0,0
755,0.331791,0.202775,2.277778,2.833333,35.495692,2.267862,9.518362,2.020549,2.310195,2.325159,...,0,1,0,0,1,0,0,0,0,0
756,0.498937,0.265850,1.850000,2.700000,79.918731,2.196267,11.716337,3.422924,3.916176,1.380058,...,0,0,0,0,0,0,0,0,0,0

In [92]:
###################################  IDO_TDO

In [108]:
target = pd.read_csv('multitarget.csv')

    ido_tdo
0        AA
1        II
2        AI
3        II
4        II
..      ...
752      II
753      II
754      IA
755      AI
756      AA

[757 rows x 1 columns]

In [109]:
encoder = LabelEncoder()

In [110]:
y_label = encoder.fit_transform(target['ido_tdo'])

In [117]:
estimator = LinearSVC(dual=False, max_iter=10000)

In [118]:
rfe = RFE(estimator, n_features_to_select=50, step=1)

In [119]:
rfe3 = rfe.fit(x_scaled, y_label)

In [123]:
idotdo_des_rfe = pd.DataFrame(x, columns=x.columns[rfe3.support_])
idotdo_des_rfe.to_csv('idotdo_des_rfe.csv', index_label=False)

In [124]:
pd.read_csv('idotdo_des_rfe.csv')

,NumValenceElectrons,MaxPartialCharge,FpDensityMorgan2,FpDensityMorgan3,BCUT2D_CHGHI,BalabanJ,BertzCT,Chi2n,Chi2v,Chi3n,...,MolMR,fr_NH0,fr_Nhpyrrole,fr_amide,fr_amidine,fr_aniline,fr_bicyclic,fr_ether,fr_furan,fr_pyridine
0,96,0.265850,1.850000,2.700000,2.299512,2.196267,959.735009,4.583717,4.583717,3.422924,...,70.7305,2,0,0,0,0,4,0,0,0
1,118,0.237258,1.826087,2.565217,2.398429,2.078932,886.505066,7.114813,7.835053,5.264118,...,91.2060,0,0,0,0,0,5,0,1,0
2,96,0.265850,1.850000,2.700000,2.297007,2.213612,959.735009,4.583717,5.020153,3.424103,...,75.7825,2,0,0,0,0,4,0,0,0
3,114,0.141781,1.250000,2.000000,2.141598,1.978942,1147.880205,5.917334,5.917334,4.531742,...,98.2065,1,1,0,0,0,6,0,0,0
4,76,0.315479,2.266667,2.933333,2.197032,2.903274,556.293908,2.882802,2.882802,1.992077,...,50.0202,2,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,102,0.067149,2.210526,3.052632,2.226436,1.771904,568.816461,5.246409,6.100746,3.983299,...,80.2482,1,1,0,0,1,1,0,0,0
753,90,0.068191,2.411765,3.235294,2.137116,1.805917,516.200028,4.458764,5.374440,3.224730,...,73.3081,1,1,0,0,1,1,0,0,0
754,118,0.237313,1.913043,2.652174,2.394416,2.042118,854.494834,7.033101,7.033101,5.213113,...,84.6918,0,0,0,0,0,5,0,1,0
755,94,0.202775,2.277778,2.833333,2.149948,2.267862,600.393973,3.200566,3.607766,2.020549,...,62.0666,3,0,0,1,2,0,0,0,0
756,96,0.265850,1.850000,2.700000,2.296868,2.196267,959.735009,4.583717,5.499393,3.422924,...,78.4725,2,0,0,0,0,4,0,0,0